name: secureboot-runner.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        export NODE_ENV=production
        export NVM_DIR=~/.nvm
        source ~/.nvm/nvm.sh
        cd ota-server
        touch .env
        echo 'DATABASE_URL: ${{ secrets.DATABASE_URL }}' >> .env
        echo 'SECRET_KEY: ${{ secrets.SECRET_KEY }}' >> .env
        echo 'JWT_KEY: ${{ secrets.JWT_KEY }}' >> .env
        echo 'JWT_REFRESH_KEY: ${{ secrets.JWT_REFRESH_KEY }}' >> .env
        echo 'SESSION_EXPIRY: ${{ secrets.SESSION_EXPIRY }}' >> .env
        echo 'REFRESH_TOKEN_EXPIRY: ${{ secrets.REFRESH_TOKEN_EXPIRY }}' >> .env
        echo 'COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}' >> .env
        echo 'WHITELISTED_DOMAINS: ${{ secrets.WHITELISTED_DOMAINS }}' >> .env
        npm install
        cd ../ui
        npm install
        npm run build
        cd ..
        pm2 stop 0
        pm2 start 0
        pm2 save
        sudo service nginx restart